import { useEffect, useState } from "react";
import { FiAlertTriangle, FiCheckCircle, FiCpu, FiDollarSign, FiShield, FiTarget, FiTrendingDown } from "react-icons/fi";
import toast from "react-hot-toast";
import { getExpenses, getMonthlyPrediction, getOverspendingAlerts, getSavingsInsights } from "../services/api";
import { useCurrency } from "../context/CurrencyContext";
import { groupBy, titleCase } from "../utils/finance";

export default function Insights() {
  const { formatMoney } = useCurrency();
  const money = formatMoney;
  const [saving, setSaving] = useState(null); const [alerts, setAlerts] = useState(null); const [prediction, setPrediction] = useState(null); const [expenses, setExpenses] = useState([]); const [loading, setLoading] = useState(true);
  const loadInsights = () => { const now = new Date(); setLoading(true); Promise.allSettled([getSavingsInsights(), getOverspendingAlerts(now.getMonth() + 1, now.getFullYear()), getMonthlyPrediction(now.getMonth() + 1, now.getFullYear()), getExpenses()]).then(([savings, overspending, forecast, expenseData]) => { if (savings.status === "fulfilled") setSaving(savings.value); if (overspending.status === "fulfilled") setAlerts(overspending.value); if (forecast.status === "fulfilled") setPrediction(forecast.value); if (expenseData.status === "fulfilled") setExpenses(expenseData.value.expenses || []); if ([savings, overspending, forecast, expenseData].every((result) => result.status === "rejected")) toast.error("Insights are unavailable while the API is offline"); }).finally(() => setLoading(false)); };
  useEffect(() => { Promise.resolve().then(loadInsights); window.addEventListener("smartbudget:budgets-changed", loadInsights); return () => window.removeEventListener("smartbudget:budgets-changed", loadInsights); }, []);
  const budgetItems = alerts?.budgets || []; const risky = budgetItems.filter((item) => item.status === "overspending" || item.status === "warning"); const totalBudget = budgetItems.reduce((sum, item) => sum + Number(item.budget || 0), 0); const totalSpent = budgetItems.reduce((sum, item) => sum + Number(item.spent || 0), 0); const healthScore = totalBudget > 0 ? Math.max(0, Math.round(((totalBudget - totalSpent) / totalBudget) * 100)) : null; const topSpending = Object.entries(groupBy(expenses, (expense) => titleCase(expense.category))).sort((a, b) => b[1] - a[1])[0]; const generatedInsights = [...risky.map((item) => `${item.category} is at ${item.usage_percentage.toFixed(0)}% of its budget. Reduce spending to stay within the limit.`), ...budgetItems.filter((item) => item.usage_percentage < 50).map((item) => `${item.category} spending is healthy at ${item.usage_percentage.toFixed(0)}% of its budget.`), topSpending && `Largest spending category: ${topSpending[0]} at ${money(topSpending[1])}.`, prediction?.total_budget > 0 && prediction.predicted_month_end > prediction.total_budget && `Projected spending is ${money(prediction.predicted_month_end - prediction.total_budget)} above the tracked budget.`].filter(Boolean).slice(0, 3);
  return <div><div className="page-heading"><div><p className="eyebrow">Smart assistant</p><h1>AI insights</h1><p className="muted">Your finances look healthy. Here are clear signals and next best actions.</p></div><div className="ai-badge"><FiCpu /> SmartBudget AI</div></div>
    {loading ? <div className="insights-grid">{[1,2,3,4].map((item) => <div className="card skeleton insight-skeleton" key={item} />)}</div> : <>{!budgetItems.length && <div className="card empty-state">No budgets configured yet.</div>}<div className="insights-grid"><div className="card insight-hero"><div className="insight-icon"><FiShield /></div><p className="eyebrow">Financial health</p><h2>{healthScore == null ? "No budgets configured yet." : healthScore >= 80 ? "Your finances look healthy" : "Worth a closer look"}</h2><p>{healthScore == null ? "Create a monthly budget to receive a data-backed health score." : `${healthScore}% of your budget capacity remains across tracked categories.`}</p><div className="health-meter"><span style={{ width: `${healthScore || 0}%` }} /></div><small>{healthScore == null ? "Awaiting budget data" : `${healthScore}% healthy capacity`}</small></div><div className="card insight-card"><div className="insight-heading"><span className="insight-icon green"><FiTrendingDown /></span><span><b>Savings opportunity</b><small>From your spending patterns</small></span></div>{saving?.potential_saving ? <><h2>{money(saving.potential_saving)}<small>/ month</small></h2><p className="muted">{saving.message}</p><div className="insight-source"><FiTarget /> Focus area: {saving.category}</div></> : <div className="empty-state">Add more expenses for a personalized savings suggestion.</div>}</div><div className="card insight-card"><div className="insight-heading"><span className="insight-icon amber"><FiAlertTriangle /></span><span><b>Budget watch</b><small>Categories that need attention</small></span></div>{risky.length ? risky.slice(0, 2).map((item) => <div className="alert-row" key={item.category}><span>{item.category}</span><b>{item.usage_percentage}% used</b></div>) : <div className="success-message"><FiCheckCircle /> No overspending alerts</div>}</div><div className="card insight-card"><div className="insight-heading"><span className="insight-icon blue"><FiDollarSign /></span><span><b>Month-end outlook</b><small>AI projection</small></span></div><h2>{money(prediction?.predicted_month_end)}</h2><p className="muted">Projected total spending by the end of this month.</p><div className="insight-source"><FiCpu /> {prediction?.prediction_method?.replaceAll("_", " ")}</div></div></div><div className="card recommendations"><div className="card-title"><div><h2>Data-backed insights</h2><span>Generated from your tracked spending</span></div></div><div className="recommendation-grid">{generatedInsights.length ? generatedInsights.map((insight, index) => <div key={insight}><span className="recommendation-number">{String(index + 1).padStart(2, "0")}</span><b>{insight}</b></div>) : <div><b>Keep tracking expenses</b><p className="muted">More spending data will unlock category-level insights.</p></div>}</div></div></>}</div>;
}
