import { FiAward, FiDownload, FiEdit3, FiShield, FiTrendingUp, FiTrash2 } from "react-icons/fi";
import toast from "react-hot-toast";
import { useCurrency } from "../context/CurrencyContext";

export default function Profile() {
  const { formatMoney } = useCurrency();
  return <div className="profile-page"><div className="page-heading"><div><p className="eyebrow">Your workspace</p><h1>Profile</h1><p className="muted">A clearer picture of your SmartBudget journey.</p></div><button className="btn btn-primary"><FiEdit3 /> Edit profile</button></div><div className="profile-layout"><section className="card profile-card profile-hero"><div className="profile-avatar">P</div><div><h2>Pari Dubey</h2><p className="muted">Personal SmartBudget workspace</p><span className="status-badge"><FiShield /> Workspace active</span></div><div className="profile-meta"><span>Started tracking</span><b>September 2026</b></div><div className="profile-actions"><button className="btn btn-ghost" onClick={() => toast.success("Export is being prepared")}><FiDownload /> Export data</button></div></section><section className="profile-stat-grid"><div className="card profile-stat"><span>Monthly expenses</span><strong>{formatMoney(18420)}</strong><small>↓ 8.4% vs last month</small></div><div className="card profile-stat"><span>Budgets created</span><strong>6</strong><small>2 currently on track</small></div><div className="card profile-stat"><span>Transactions</span><strong>128</strong><small>Across 7 categories</small></div><div className="card profile-stat"><span>AI suggestions used</span><strong>42</strong><small>92% acceptance rate</small></div></section></div><div className="profile-bottom"><section className="card list-card"><div className="card-title"><h2>Achievements</h2><span>Keep going</span></div><div className="achievement-row"><span className="achievement-icon"><FiAward /></span><div><b>Mindful spender</b><p className="muted">Stayed within budget for 7 consecutive days.</p></div><strong>+120 XP</strong></div><div className="achievement-row"><span className="achievement-icon green"><FiTrendingUp /></span><div><b>First savings goal</b><p className="muted">Created your first monthly savings target.</p></div><strong>+80 XP</strong></div></section><section className="card list-card"><div className="card-title"><h2>Workspace controls</h2></div><div className="list-row"><p>Current savings<small>Monthly goal progress</small></p><b className="amount-positive">{formatMoney(5680)}</b></div><div className="list-row"><p>Security<small>Local workspace preferences</small></p><FiShield className="muted" /></div><button className="danger-link" onClick={() => toast.error("Account deletion is unavailable without an account service")}><FiTrash2 /> Delete workspace</button></section></div></div>;
}


