import { useState } from "react";
import { FiBell, FiChevronRight, FiShield, FiTrash2, FiDownload } from "react-icons/fi";
import toast from "react-hot-toast";

const Toggle = ({ checked, onChange }) => <button type="button" aria-pressed={checked} className={`switch ${checked ? "on" : ""}`} onClick={() => onChange(!checked)}><span /></button>;
export default function Settings() {
  const [notifications, setNotifications] = useState(true); const [ai, setAi] = useState(true); const [privacy, setPrivacy] = useState(true);
  return <div><div className="page-heading"><div><p className="eyebrow">Workspace controls</p><h1>Settings</h1><p className="muted">Make SmartBudget feel distinctly yours.</p></div><button className="btn btn-primary" onClick={() => toast.success("Preferences saved")}>Save changes</button></div><div className="settings-grid"><section className="card settings-section"><div className="settings-section-title"><span className="settings-icon">◒</span><div><h2>Workspace</h2><p>SmartBudget uses its focused dark interface.</p></div></div><div className="setting-row"><div><b>Language</b><p>Choose your preferred language.</p></div><button className="setting-select">English <FiChevronRight /></button></div></section><section className="card settings-section"><div className="settings-section-title"><span className="settings-icon"><FiBell /></span><div><h2>Notifications</h2><p>Stay informed without the noise.</p></div></div><div className="setting-row"><div><b>Spending alerts</b><p>Get notified when a category is trending high.</p></div><Toggle checked={notifications} onChange={setNotifications} /></div><div className="setting-row"><div><b>AI recommendations</b><p>Receive useful suggestions based on your habits.</p></div><Toggle checked={ai} onChange={setAi} /></div></section><section className="card settings-section"><div className="settings-section-title"><span className="settings-icon"><FiShield /></span><div><h2>Privacy & security</h2><p>Control how your financial data is handled.</p></div></div><div className="setting-row"><div><b>Private workspace</b><p>Your data is only visible to you.</p></div><Toggle checked={privacy} onChange={setPrivacy} /></div><div className="setting-row"><div><b>Security review</b><p>Review sessions and account access.</p></div><button className="setting-select">Review <FiChevronRight /></button></div></section><section className="card settings-section"><div className="settings-section-title"><span className="settings-icon"><FiDownload /></span><div><h2>Data & exports</h2><p>Take your data with you anytime.</p></div></div><div className="setting-row"><div><b>Export expenses</b><p>Download a CSV of your transaction history.</p></div><button className="btn btn-ghost" onClick={() => toast.success("Export is being prepared")}><FiDownload /> Export</button></div><div className="setting-row danger-setting"><div><b>Danger zone</b><p>Reset local preferences or delete your account.</p></div><button className="danger-link" onClick={() => toast.error("Reset requires confirmation")}><FiTrash2 /> Reset app</button></div></section></div></div>;
}
